baseURL = 'http://example.org/'
title = 'SMU Smart City Society'
theme = 'SmartCity'


[params]
  introTitle = "SMU Smart City Society"
  introSubtitle = "Hi, I am smart"
  introPhoto = "/scnexco.jpg"
  logo = "/scnlogo.png"

    # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "© 2022 by SMU Smart City Society"
  favicon = "/scnfvicon.jpg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-green-900"

  # The page bundle that is shown on the front page
  frontBundle = "news"


[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[[menu.main]]
    name = "Top Post"
    url = "/news/emoji-support/"
    weight = 3

[[menu.main]]
    name = "Exco"
    url = "customHTML/index.html"
    weight = 4

[[menu.main]]
    name = "News"
    url = "news"
    weight = 5








[params.homepage.social]
  # Global params xommon for both languages
  title = "Socials"
  description = "You can find us here"
  instagram = "https://www.instagram.com/smu.smartcitysoc/?hl=en"
  linkedin = "https://www.linkedin.com/company/smu-smartcity-society/?originalSubdomain=sg"






[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true





 
